name: deploy-email-templates
on:
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Preview
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Build
        run: |
          npm install
      - name: Deploy
        run: |
          ./.github/scripts/deploy_email_templates.sh
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
